/**
 * Balanced starting point for regular signal activity.
 *
 * ICT and chart-pattern setups are evaluated independently in hybrid mode.
 * Confirmation, fresh-breakout checks, and reward/risk floors remain enabled;
 * lower-frequency context checks reduce signal starvation without promising
 * profitability.
 */
export const RECOMMENDED_SCANNER_SETTINGS = {
  strategyMode: 'hybrid',
  minScore: 72,
  minEntryATR: 0.5,
  maxEntryATR: 4,
  telegramMaxATR: 2,
  maxGapPercent: 3,
  requireHtfAligned: false,
  requireLiquidityEdge: true,
  requireSweepOrFvg: true,
  smcConfig: {
    setupTf: '15m',
    htfTf: '1h',
    sweepLookbackBars: 32,
    maxBosAgeBars: 20,
  },
  chartPatternConfig: {
    patternTfs: ['15m', '30m', '1h'],
    enabledPatterns: 'ALL',
    nearEntryOnLivePrice: false,
    weakBreakoutPromote: false,
    weakBreakoutMaxChaseR: 0.35,
    minSignalScore: 55,
    minRelativeVolume: 1.2,
    minRR: 1.2,
    breakoutAtrMin: 0.15,
    maxBreakoutDistanceATR: 1.8,
    minBodyRatio: 0.45,
    requireVolumeConfirmation: false,
    requireHtfAlign: false,
    minConfluencePillars: 1,
    minTp1RR: 1.0,
    universalEngineEnabled: true,
    minFinalScore: 55,
    minPatternScore: 40,
    minLocationScore: 40,
    minRejectionScore: 25,
    minReversalZoneScore: 35,
    minReversalLocationScore: 45,
    waveAnalysisEnabled: false,
    nearMaxPatternAge: 30,
    nearStaleRescue: true,
    nearStaleRescueMaxAge: 150,
    nearStaleRescueMaxGapATR: 1.5,
    failedBreakoutInvalidate: true,
    failedBreakoutBufferATR: 0.5,
    failedBreakoutConfirmCandles: 2,
    gateModes: {
      htf: 'soft',
      volume: 'soft',
      retest: 'soft',
      pillars: 'soft',
      smc: 'soft',
      fib: 'soft',
      rejectionZone: 'soft',
      rejection: 'soft',
      location: 'soft',
      midRange: 'soft',
      wave: 'soft',
      blockedPath: 'soft',
      tp1rr: 'hard',
      tp2rr: 'hard',
      rsiDiv: 'soft',
      ema: 'soft',
    },
    rsiPeriod: 14,
    emaFast: 21,
    emaSlow: 50,
  },
};